services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [appnet]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    networks: [appnet]
    volumes:
      - redisdata:/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      ROLE: web
    depends_on:
      - postgres
      - redis
    networks: [appnet]
    # Доступ к ModemManager на ХОСТЕ
    volumes:
      - /var/run/dbus:/var/run/dbus:ro
      - /run/ModemManager:/run/ModemManager:ro
      - staticdata:/static
    restart: always

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      ROLE: worker
      # Настройки для чтения SMS через pyserial
      MODEM_PORT: /dev/ttyUSB1
      MODEM_BAUDRATE: 115200
      MAX_SMS_PER_ITERATION: 10
    depends_on:
      - postgres
      - redis
    networks: [appnet]
    # Доступ к модему для чтения SMS через pyserial
    privileged: true
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
      - /dev/serial/by-id:/dev/serial/by-id
    restart: always

  beat:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      ROLE: beat
    depends_on:
      - postgres
      - redis
    networks: [appnet]
    restart: always

  nginx:
    image: nginx:1.27
    depends_on:
      - web
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - /dev/null:/etc/nginx/conf.d/default.conf
      - staticdata:/static:ro
    ports:
      - "80:80"
    networks: [appnet]
    restart: always


networks:
  appnet:

volumes:
  pgdata:
  redisdata:
  staticdata:
