# Generated by Django 5.2.6 on 2025-09-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=255)),
                ('post_id', models.CharField(max_length=255)),
                ('issue_id', models.CharField(max_length=250)),
            ],
        ),
    ]
