# Generated by Django 5.2.6 on 2025-09-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprint',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('acked', 'Подтверждён')], db_index=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='fingerprint',
            name='issue_id',
            field=models.CharField(max_length=255),
        ),
    ]
