# Generated by Django 5.2.6 on 2025-09-29 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_fingerprint_status_alter_fingerprint_issue_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fingerprint',
            name='fingerprint',
        ),
    ]
