# Generated by Django 5.2.6 on 2025-09-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_remove_fingerprint_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprint',
            name='acked_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
