# Generated by Django 5.2.6 on 2025-09-29 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_fingerprint_acked_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fingerprint',
            new_name='Events',
        ),
    ]
