# Generated by Django 5.2.6 on 2025-09-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_rename_fingerprint_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='sms_sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='sms_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='post_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
