# Generated by Django 5.2.6 on 2025-09-29 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_events_sms_sent_events_sms_text_alter_events_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='sms_sent',
            new_name='done',
        ),
    ]
