# Generated by Django 5.2.6 on 2025-10-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_rename_sms_sent_events_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='done',
        ),
        migrations.AlterField(
            model_name='events',
            name='issue_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('acked', 'Подтверждён'), ('sent', 'Отправлен')], db_index=True, default='new', max_length=20),
        ),
    ]
