# Generated by Django 5.2.6 on 2025-10-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0008_remove_events_done_alter_events_issue_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alertname', models.CharField(db_index=True, help_text='Название алерта из SMS (например: HostSystemdServiceCrashed)', max_length=255, unique=True, verbose_name='Alert Name')),
                ('description', models.TextField(help_text='Описание на русском языке', verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Описание алерта',
                'verbose_name_plural': 'Описания алертов',
                'ordering': ['alertname'],
            },
        ),
    ]
