# Generated by Django 5.2.6 on 2025-12-22 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_alertdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 22, 7, 34, 39, 476565, tzinfo=datetime.timezone.utc), verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('acked', 'Подтверждён'), ('sent', 'Отправлен'), ('skipped', 'Пропущен')], db_index=True, default='new', max_length=20),
        ),
    ]
